language: bash

matrix:

  include:

    - os: linux
      dist: bionic

before_script:
  - sudo pip install --upgrade setuptools
  - sudo pip3 install --upgrade setuptools

script:
  - ./install.sh

