language: bash

matrix:
  include:
    -
    - os: linux
      dist: bionic
      apt:
        packages:
          - shellcheck
        update: true
      script:
        - shellcheck install.sh
        - bash -x ./install.sh
        - valet.sh

    - os: osx
      osx_image: xcode11

    - os: osx
      osx_image: xcode9.4

script:
  - bash -x ./install.sh
  - valet.sh

