language: bash

matrix:
  include:
    - os: linux
      dist: bionic
      apt:
        packages:
          - shellcheck
        update: true
      script:
        - shellcheck install.sh
        - shellcheck include.sh
        - bash -x ./install.sh
        - valet.sh
    - os: osx
      osx_image: xcode12.2
      script:
        - bash -x ./install.sh
        - valet.sh
    - os: osx
      osx_image: xcode11.6
      script:
        - bash -x ./install.sh
        - valet.sh
