jobs:
- job: ubuntu-18.04
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: |
      ./install.sh
      valet.sh
    displayName: Test Installation
    failOnStderr: true

- job: macOS-10.13
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: |
      sudo rm -rf /Applications/Xcode.app /Library/Developer/CommandLineTools
      sudo pkgutil --forget com.apple.pkg.CLTools_Executables
      sudo xcode-select --reset
    displayName: Prepare
  - bash: |
      ./install.sh
      valet.sh
    displayName: Test Installation
    failOnStderr: true

- job: macOS-10.14
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: |
      sudo rm -rf /Applications/Xcode.app /Library/Developer/CommandLineTools
      sudo pkgutil --forget com.apple.pkg.CLTools_Executables
      sudo xcode-select --reset
    displayName: Prepare
  - bash: |
      ./install.sh
      valet.sh
    displayName: Test Installation
    failOnStderr: true