name: 'build'

on:
  schedule:
    - cron: "30 4 * * 0"
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
  install-on-ubuntu-2004:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
  install-on-ubuntu-2204:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
  install-on-macos-11:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
  install-on-macos-12:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
  install-on-macos-1015:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash